"""In table user added public_key

Revision ID: 4ab823f131d5
Revises: 7c6a5f48c3f0
Create Date: 2025-06-27 22:03:49.930376

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4ab823f131d5'
down_revision: str | None = '7c6a5f48c3f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_key', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'public_key')
    # ### end Alembic commands ###
